spring:
  ai:
    model:
      chat: "none"
    ollama:
      base-url: "http://localhost:11434"
      embedding:
        options:
          model: "qwen3-embedding:0.6b"
      init:
        pull-model-strategy: "ALWAYS"
        timeout: "10m"
    vectorstore:
      pgvector:
        initialize-schema: true
    mcp:
      server:
        protocol: "STREAMABLE"
        instructions: "This HTTP server provides data for the Simpsons episodes dataset."
        name: "simpsons-episodes-mcp-server"
        type: "SYNC"
        version: "@project.version@"
        streamable-http:
          mcp-endpoint: "/mcp"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "changeme"
